# Generated by Django 4.1 on 2023-01-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('', ''), ('FOL', 'Follow'), ('UNF', 'Unfollow'), ('UND', 'Undo'), ('ACC', 'Accept'), ('CRE', 'Create'), ('NTE', 'Note'), ('DEL', 'Delete'), ('TOM', 'Tombstone'), ('LKE', 'Like'), ('ANN', 'Announce')], default='', max_length=3, verbose_name='Type'),
        ),
    ]
