# Generated by Django 4.1 on 2023-02-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0002_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='context',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Context'),
        ),
        migrations.AddField(
            model_name='activity',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='Disabled'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('', ''), ('FOL', 'Follow'), ('UNF', 'Unfollow'), ('UND', 'Undo'), ('ACC', 'Accept'), ('CRE', 'Create'), ('NTE', 'Note'), ('DEL', 'Delete'), ('TOM', 'Tombstone'), ('LKE', 'Like'), ('ANN', 'Announce'), ('BLK', 'Block')], default='', max_length=3, verbose_name='Type'),
        ),
    ]
