# Generated by Django 4.1 on 2025-06-07 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0004_alter_activity_options_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_uri',
            field=models.URLField(blank=True, db_index=True, default='', verbose_name='Object URI'),
        ),
    ]
