# Generated by Django 4.1 on 2026-06-13 20:55

import datetime
from django.db import migrations, models
import messy_fediverse.models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0007_activity_activity_data_alter_activity_activity_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='in_reply_to_uri',
            field=models.URLField(blank=True, default='', verbose_name='In reply to'),
        ),
        migrations.AddField(
            model_name='activity',
            name='object_type',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Object Type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='thread_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc), verbose_name='Thread updated at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activity',
            name='updated_by_activity_uri',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Updated by activity'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('', ''), ('CCH', 'Cache'), ('FOL', 'Follow'), ('UNF', 'Unfollow'), ('UND', 'Undo'), ('ACC', 'Accept'), ('CRE', 'Create'), ('UPD', 'Update'), ('NTE', 'Note'), ('DEL', 'Delete'), ('TOM', 'Tombstone'), ('LKE', 'Like'), ('ANN', 'Announce'), ('BLK', 'Block')], default='', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='self_json',
            field=models.FileField(blank=True, null=True, upload_to=messy_fediverse.models.get_upload_path, verbose_name='Raw JSON'),
        ),
    ]
