# Generated by Django 4.1 on 2026-06-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0008_activity_in_reply_to_uri_activity_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updated_by_activity_uri',
            field=models.URLField(blank=True, default='', max_length=255, verbose_name='Updated by activity'),
        ),
    ]
