# Generated by Django 4.1 on 2023-01-08 18:50

from django.db import migrations, models
import django.db.models.deletion
import messy_fediverse.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('uri', models.URLField(unique=True, verbose_name='Activity URI')),
                ('activity_type', models.CharField(blank=True, choices=[('', ''), ('FOL', 'Follow'), ('UNF', 'Unfollow'), ('UND', 'Undo'), ('ACC', 'Accept'), ('CRE', 'Create'), ('NTE', 'Note'), ('DEL', 'Delete'), ('THO', 'Thombstone'), ('LKE', 'Like')], default='', max_length=3, verbose_name='Type')),
                ('actor_uri', models.URLField(blank=True, default='', verbose_name='Actor URI')),
                ('object_uri', models.URLField(blank=True, default='', verbose_name='Object URI')),
                ('self_json', models.FileField(null=True, upload_to=messy_fediverse.models.get_upload_path, verbose_name='Raw JSON')),
                ('incoming', models.BooleanField(default=False, verbose_name='Is incoming')),
            ],
        ),
        migrations.CreateModel(
            name='FederatedEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(unique=True, verbose_name='URL')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
            ],
        ),
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.URLField(unique=True, verbose_name='Actor URI')),
                ('object_uri', models.URLField(blank=True, default='', verbose_name='Followed object URI')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('accepted', models.BooleanField(default=False, verbose_name='Accepted')),
                ('activity', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messy_fediverse.activity')),
                ('endpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='messy_fediverse.federatedendpoint')),
            ],
        ),
    ]
