# Generated by Django 4.1 on 2025-06-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0003_activity_context_activity_disabled_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('', ''), ('FOL', 'Follow'), ('UNF', 'Unfollow'), ('UND', 'Undo'), ('ACC', 'Accept'), ('CRE', 'Create'), ('UPD', 'Update'), ('NTE', 'Note'), ('DEL', 'Delete'), ('TOM', 'Tombstone'), ('LKE', 'Like'), ('ANN', 'Announce'), ('BLK', 'Block')], default='', max_length=3, verbose_name='Type'),
        ),
    ]
