# Generated by Django 4.1 on 2025-08-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0005_alter_activity_object_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='processing_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Unprocessed'), (10, 'Processing'), (20, 'Done')], default=0, verbose_name='Processing status'),
        ),
    ]
