# Generated by Django 4.1 on 2025-08-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0006_activity_processing_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='activity_data',
            field=models.JSONField(blank=True, null=True, verbose_name='Activity data'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(blank=True, choices=[('', ''), ('CCH', 'Cache'), ('FOL', 'Follow'), ('UNF', 'Unfollow'), ('UND', 'Undo'), ('ACC', 'Accept'), ('CRE', '   Create'), ('UPD', 'Update'), ('NTE', 'Note'), ('DEL', 'Delete'), ('TOM', 'Tombstone'), ('LKE', 'Like'), ('ANN', 'Announce'), ('BLK', 'Block')], default='', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='context',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='Context'),
        ),
    ]
