# Generated by Django 4.1 on 2026-07-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0009_alter_activity_updated_by_activity_uri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='processing_status',
            field=models.IntegerField(blank=True, default=0, verbose_name='Processing status'),
        ),
    ]
