# Generated by Django 4.1.5 on 2026-09-20 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messy_fediverse', '0011_tag_taggedobject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
                ('mastodon_base_url', models.URLField(verbose_name='Mastodon base URL')),
                ('mastodon_access_token', models.CharField(max_length=255, verbose_name='Mastodon access token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='messy_fediverse.tag', verbose_name='Tag')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddField(
            model_name='taggedobject',
            name='meta',
            field=models.JSONField(blank=True, default=dict, verbose_name='Meta'),
        ),
        migrations.CreateModel(
            name='GroupBoost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_uri', models.URLField(verbose_name='Root URI')),
                ('comment_uri', models.URLField(blank=True, default='', verbose_name='Comment URI')),
                ('reblog_id', models.CharField(blank=True, default='', max_length=128, verbose_name='Reblog ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boosts', to='messy_fediverse.group', verbose_name='Group')),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
        migrations.AddConstraint(
            model_name='groupboost',
            constraint=models.UniqueConstraint(fields=('group', 'root_uri'), name='group_boost_unique_root'),
        ),
    ]
